extends:
  - spectral:oas

rules:
  info-version-format:
    severity: warn
    recommended: true
    message: Specs should follow semantic versioning. {{value}} is not a valid version
    given: $.info.version
    then:
      function: pattern
      functionOptions:
        match: "^[0-9]+\\.[0-9]+\\.[0-9]+$"

  server-url-must-contain-version:
    severity: warn
    recommended: true
    message: Global API version must be present in the path
    given: $.servers[*].url
    then:
      function: pattern
      functionOptions:
        match: "\\/v[1-9]+\\/"

  operation-tag-defined:
    severity: warn
    recommended: true
    message: Operation tags must be defined in global tags
    given: $.paths.*.*.tags
    then:
      function: truthy

  oas3-valid-schema-example:
    severity: warn
    recommended: true
    message: Example property type should be correct
    given: $.components.schemas..properties..example
    then:
      function: type
      functionOptions:
        type: integer  # Adjust type based on your specific schema requirements
