openapi: 3.0.0
info:
  title: Board & Management
  version: 1.0.0
  description: This is a sample API description.
  contact:
    name: API Support
    email: support@example.com
    url: https://example.com/support
servers:
  - url: 'https://mocktarget.apigee.net/json'
paths:
  /hello:
    get:
      summary: Get Hello Message
      description: Retrieve a simple hello message.
      operationId: getHelloMessage
      tags:
        - Hello
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request
