openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: 'https://rakeshkumawat-eval-test.apigee.net'
paths:
  /hello:
    get:
      summary: Get Hello Message
      description: Retrieve a simple hello message.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request
