name: konnect-gatewat-deployment

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy_to_konnect:
    runs-on: ubuntu-latest
    name: Deploying Kong Configuration
    steps:
      # Steps for deploying Kong configuration go here...

  publish-customer-api-to-portal:
    name: Publish OAS to dev portal
    needs: deploy_to_konnect
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch environment variables
        id: set_env_vars
        run: |
          echo "API_PRODUCT_NAME: ${{ vars.API_PRODUCT_NAME }}"
          echo "CONTROL_PLANE_NAME: ${{ vars.CONTROL_PLANE_NAME }}"
          echo "GATEWAY_SERVICE_NAME: ${{ vars.GATEWAY_SERVICE_NAME }}"

      - name: Check API Product is already exist or not or Creating new API product
        run: |
          response=$(curl -s --request GET \
            --url "${{ vars.ADMIN_API_URL }}/api-products" \
            --header "Authorization: ${{ secrets.KONNECT_TOKEN }}")

          if [[ $response == *"${{ vars.API_PRODUCT_NAME }}"* ]]; then
            echo "API product already exists, Please change the API product name"
            echo "API_PRODUCT_ALREADY_EXISTS=true" >> $GITHUB_ENV
            exit 1  # Terminate the job here since the product already exists
          else
            echo "API product doesn't exist, creating..."
            curl --request POST \
              --url ${{ vars.ADMIN_API_URL }}/api-products \
              --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
              --header 'Content-Type: application/json' \
              --data '{
                "name": "${{ vars.API_PRODUCT_NAME }}",
                "description": "Creating through admin api",
                "labels": {}
              }'
          fi 

      - name: Get API product ID
        run: |
          api_product_name="${{ vars.API_PRODUCT_NAME }}"

          api_product_id=$(curl --request GET \
            --url ${{ vars.ADMIN_API_URL }}/api-products \
            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
            | jq -r --arg api_product_name "$api_product_name" '.data[] | select(.name == $api_product_name) | .id // empty')

          if [ "$api_product_id" = "empty" ]; then
            echo "Error: API Product ID not found."
            exit 1
          fi

          echo "API_PRODUCT_ID=$api_product_id" >> $GITHUB_ENV

      # Other steps for publishing to the dev portal go here...
