jobs:
  deploy_to_konnect:
    runs-on: ubuntu-latest
    name: Deploying Kong Configuration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Print current working directory
        run: pwd

      - name: Verify file path
        run: ls -al ./config.json

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch environment variables and extract Product details
        id: set_env_vars
        run: |
          config=$(cat ./config.json)
          echo "Config content: $config"
          CONTROL_PLANE_NAME=$(echo "$config" | jq -r '.CONTROL_PLANE_NAME')
          APPLICATION_AUTH_STRATEGY=$(echo "$config" | jq -r '.APPLICATION_AUTH_STRATEGY')
          SERVICE_HOST=$(echo "$config" | jq -r '.SERVICE_HOST')
          echo "CONTROL_PLANE_NAME=$CONTROL_PLANE_NAME" >> $GITHUB_ENV
          echo "APPLICATION_AUTH_STRATEGY=$APPLICATION_AUTH_STRATEGY" >> $GITHUB_ENV
          echo "SERVICE_HOST=$SERVICE_HOST" >> $GITHUB_ENV

      - name: Display environment variables for verification
        run: |
          echo "CONTROL_PLANE_NAME=$CONTROL_PLANE_NAME"
          echo "APPLICATION_AUTH_STRATEGY=$APPLICATION_AUTH_STRATEGY"
          echo "SERVICE_HOST=$SERVICE_HOST"

      - name: Lint OAS spec using Spectral
        run: spectral lint ./kong-config/spec.yaml --ruleset ./kong-config/.spectral.yaml
